import type { ComponentType } from "react";
import type { IconProps } from "./types";
import * as Outline from "./outline";
import * as Filled from "./filled";

type IconComponent = ComponentType<IconProps>;

export const outlineIcons: Record<string, IconComponent> = {
  home: Outline.Home,
  inbox: Outline.Inbox,
  "file-text": Outline.FileText,
  bolt: Outline.Bolt,
  "chat-bubble": Outline.ChatBubble,
  "file-search": Outline.FileSearch,
  bell: Outline.Bell,
  "chart-bar": Outline.ChartBar,
  "file-check": Outline.FileCheck,
  user: Outline.User,
  "file-search-alt": Outline.FileSearchAlt,
  lifebuoy: Outline.Lifebuoy,
  cog: Outline.Cog,
  workspace: Outline.Workspace,
  users: Outline.Users,
  groups: Outline.Groups,
  "audit-log": Outline.AuditLog,
  microphone: Outline.Microphone,
  flag: Outline.Flag,
  "clipboard-check": Outline.ClipboardCheck,
  "check-square": Outline.CheckSquare,
  building: Outline.Building,
  "user-circle": Outline.UserCircle,
  "chevron-down": Outline.ChevronDown,
  "chevron-up": Outline.ChevronUp,
  "chevron-left": Outline.ChevronLeft,
  "chevron-right": Outline.ChevronRight,
  "chevron-down-mini": Outline.ChevronDownMini,
  "arrow-left": Outline.ArrowLeft,
  "arrow-up": Outline.ArrowUp,
  "arrow-down": Outline.ArrowDown,
  "x-mark": Outline.XMark,
  check: Outline.Check,
  "check-mini": Outline.CheckMini,
  plus: Outline.Plus,
  minus: Outline.Minus,
  pencil: Outline.Pencil,
  trash: Outline.Trash,
  clipboard: Outline.Clipboard,
  "magnifying-glass": Outline.MagnifyingGlass,
  link: Outline.Link,
  expand: Outline.Expand,
  filter: Outline.Filter,
  "drag-handle": Outline.DragHandle,
  "info-circle": Outline.InfoCircle,
  "check-circle": Outline.CheckCircle,
  "warning-triangle": Outline.WarningTriangle,
  "error-circle": Outline.ErrorCircle,
  calendar: Outline.Calendar,
  "calendar-mini": Outline.CalendarMini,
  "document-text": Outline.DocumentText,
  folder: Outline.Folder,
  people: Outline.People,
  "map-pin": Outline.MapPin,
  tag: Outline.Tag,
  "shield-check": Outline.ShieldCheck,
  "thumb-down": Outline.ThumbDown,
  "warning-exclamation": Outline.WarningExclamation,
  sun: Outline.Sun,
  moon: Outline.Moon,
  hamburger: Outline.Hamburger,
  "scorecard-check": Outline.ScorecardCheck,
  play: Outline.Play,
  pause: Outline.Pause,
  volume: Outline.Volume,
  mute: Outline.Mute,
  "triangle-down": Outline.TriangleDown,
  "triangle-right": Outline.TriangleRight,
  "ellipsis-horizontal": Outline.EllipsisHorizontal,
  dot: Outline.Dot,
  loading: Outline.Loading,
  keyboard: Outline.Keyboard,
  "simulations-min": Outline.SimulationsMin,
  "scorecards-min": Outline.ScorecardsMin,
  "personas-min": Outline.PersonasMin,
  "backend-tools-min": Outline.BackendToolsMin,
  "ai-sparkle": Outline.AiSparkle,
  "send-circle": Outline.SendCircle,
};

export const filledIcons: Record<string, IconComponent> = {
  home: Filled.HomeFilled,
  inbox: Filled.InboxFilled,
  "file-text": Filled.FileTextFilled,
  bolt: Filled.BoltFilled,
  "chat-bubble": Filled.ChatBubbleFilled,
  "file-search": Filled.FileSearchFilled,
  bell: Filled.BellFilled,
  "chart-bar": Filled.ChartBarFilled,
  "file-check": Filled.FileCheckFilled,
  user: Filled.UserFilled,
  "file-search-alt": Filled.FileSearchAltFilled,
  lifebuoy: Filled.LifebuoyFilled,
  cog: Filled.CogFilled,
  workspace: Filled.WorkspaceFilled,
  users: Filled.UsersFilled,
  groups: Filled.GroupsFilled,
  "audit-log": Filled.AuditLogFilled,
  microphone: Filled.MicrophoneFilled,
  flag: Filled.FlagFilled,
  "clipboard-check": Filled.ClipboardCheckFilled,
  "check-square": Filled.CheckSquareFilled,
  building: Filled.BuildingFilled,
  "user-circle": Filled.UserCircleFilled,
  "info-circle": Filled.InfoCircleFilled,
  "check-circle": Filled.CheckCircleFilled,
  warning: Filled.WarningFilled,
  "error-circle": Filled.ErrorCircleFilled,
  sun: Filled.SunFilled,
  moon: Filled.MoonFilled,
  "pending-dot": Filled.PendingDot,
  "active-dot": Filled.ActiveDot,
  "complete-dot": Filled.CompleteDot,
  "error-dot": Filled.ErrorDot,
  "radio-dot": Filled.RadioDot,
};

export type OutlineIconName = keyof typeof outlineIcons;
export type FilledIconName = keyof typeof filledIcons;
export type IconName = OutlineIconName | FilledIconName;
